"""Validate that the generated development lock covers every direct input."""

from __future__ import annotations

import re
import sys
from pathlib import Path

from packaging.requirements import Requirement
from packaging.version import InvalidVersion, Version


_PIN = re.compile(r"^([A-Za-z0-9_.-]+)==([^\s;]+)")
_SHA256 = re.compile(r"(?m)^\s+--hash=sha256:([0-9a-f]{64})(?:\s|\\|$)")


def _normalized(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def _parse_lock(text: str) -> tuple[dict[str, str], list[str]]:
    pins: dict[str, str] = {}
    errors: list[str] = []
    lines = text.splitlines()
    pin_indexes = [index for index, raw in enumerate(lines) if _PIN.match(raw.strip())]
    for position, index in enumerate(pin_indexes):
        match = _PIN.match(lines[index].strip())
        assert match is not None
        name = _normalized(match.group(1))
        if name in pins:
            errors.append(f"duplicate lock entry: {name}")
        pins[name] = match.group(2)
        end = pin_indexes[position + 1] if position + 1 < len(pin_indexes) else len(lines)
        if not _SHA256.search("\n".join(lines[index:end])):
            errors.append(f"lock entry is missing a sha256 hash: {name}")
    return pins, errors


def validate(input_path: Path, lock_path: Path) -> list[str]:
    direct = {
        _normalized(requirement.name): requirement
        for raw in input_path.read_text(encoding="utf-8").splitlines()
        if (line := raw.strip()) and not line.startswith("#")
        for requirement in (Requirement(line),)
    }
    text = lock_path.read_text(encoding="utf-8")
    pins, errors = _parse_lock(text)
    if "autogenerated by pip-compile" not in text:
        errors.append("lock file is missing the pip-compile generated header")
    for name in sorted(direct.keys() - pins.keys()):
        errors.append(f"direct requirement is not pinned: {name}")
    for name in sorted(direct.keys() & pins.keys()):
        requirement = direct[name]
        try:
            version = Version(pins[name])
        except InvalidVersion:
            errors.append(f"direct requirement has an invalid pinned version: {name}=={pins[name]}")
            continue
        if requirement.specifier and version not in requirement.specifier:
            errors.append(
                f"direct requirement pin violates input constraint: {name}=={version} not in {requirement.specifier}"
            )
    if not pins:
        errors.append("lock file contains no exact pins")
    return errors


def main() -> int:
    errors = validate(Path("requirements-dev.in"), Path("requirements-dev.txt"))
    for error in errors:
        print(f"ERROR: {error}", file=sys.stderr)
    return 1 if errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
