"""Validate that the generated development lock covers every direct input."""

from __future__ import annotations

import re
import sys
from pathlib import Path

from packaging.requirements import Requirement
from packaging.version import InvalidVersion, Version


_PIN = re.compile(r"^([A-Za-z0-9_.-]+)==([^\s;]+)")


def _normalized(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def validate(input_path: Path, lock_path: Path) -> list[str]:
    direct = {
        _normalized(requirement.name): requirement
        for raw in input_path.read_text(encoding="utf-8").splitlines()
        if (line := raw.strip()) and not line.startswith("#")
        for requirement in (Requirement(line),)
    }
    pins: dict[str, str] = {}
    errors: list[str] = []
    text = lock_path.read_text(encoding="utf-8")
    if "autogenerated by pip-compile" not in text:
        errors.append("lock file is missing the pip-compile generated header")
    for raw in text.splitlines():
        match = _PIN.match(raw.strip())
        if not match:
            continue
        name = _normalized(match.group(1))
        if name in pins:
            errors.append(f"duplicate lock entry: {name}")
        pins[name] = match.group(2)
    for name in sorted(direct.keys() - pins.keys()):
        errors.append(f"direct requirement is not pinned: {name}")
    for name in sorted(direct.keys() & pins.keys()):
        requirement = direct[name]
        try:
            version = Version(pins[name])
        except InvalidVersion:
            errors.append(f"direct requirement has an invalid pinned version: {name}=={pins[name]}")
            continue
        if requirement.specifier and version not in requirement.specifier:
            errors.append(
                f"direct requirement pin violates input constraint: {name}=={version} not in {requirement.specifier}"
            )
    if not pins:
        errors.append("lock file contains no exact pins")
    return errors


def main() -> int:
    errors = validate(Path("requirements-dev.in"), Path("requirements-dev.txt"))
    for error in errors:
        print(f"ERROR: {error}", file=sys.stderr)
    return 1 if errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
